agent:
  id: ""
  name: "RedGhost"
  manager_url: "http://192.168.60.135:55000"
  registration_key: ""
  heartbeat_interval: 60

monitoring:
  file_system:
    enabled: true
    paths:
      - "/home/redghost/Desktop"
      - "/home/redghost/Documents"
      - "/home/redghost/Downloads"
    extensions:
      - .pdf
      - .docx
      - .xlsx
      - .txt
      - .csv
    exclude_patterns:
      - "*/node_modules/*"
      - "*/.git/*"

  clipboard:
    enabled: true
    poll_interval: 2

  usb:
    enabled: true
    poll_interval: 5

  network:
    enabled: false

classification:
  local:
    enabled: true
    patterns:
      - credit_card
      - ssn
      - email

performance:
  max_events_per_minute: 100
  max_event_size: 1048576
  batch_size: 10
  queue_size: 1000

logging:
  level: INFO
  file: "/etc/cybersentinel/logs/agent.log"
  max_size: 10485760
  max_files: 5
